apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-server
  namespace: production
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: redis-server
    spec:
      containers:
      - name: redis-master
        image: redis:5.0.5-alpine
        command: ["redis-server"]
        args: ["--appendonly", "yes"]
        ports:
        - containerPort: 6379
        volumeMounts:
          - name: redis-data
            mountPath: /data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data
      restartPolicy: Always
